### ISSUE TITLE
4.7	default glyph is empty – question

### ISSUE THREAD

**Issue by RafalBuchner** [LettError/DesignspaceProblems#6]
> 4.7 default glyph is empty

is it being thrown, when the default glyph doesn't exist, or just when the glyph has no data in it but exists in the font object? or both?

**Comment by LettError** [comment]
First all glyphnames are collected from all masters. Then for each name in that list, it checks if it has an entry in the default font. It doesn't check if the glyph exists but may be empty. Existing but empty default glyph would show up in outline tests, right?

https://github.com/LettError/DesignspaceProblems/blob/master/Lib/designspaceProblems/__init__.py#L428
