### ISSUE TITLE
It would be helpful for DesignSpace Problems to include check for inconsistent unicodes

### ISSUE THREAD

**Issue by arrowtype** [LettError/DesignspaceProblems#7]
I've just learned [the hard way](https://github.com/arrowtype/recursive/issues/213) how painful it can be if unicodes mismatch in sources when you are trying to build a variable font.

Because of this, I believe it would be useful for DesignspaceProblems to include a check for inconsistent unicodes between fonts. If this were in place, it would presumably be a little faster for designers to catch this issue.

Thanks for such a useful tool!

**Comment by LettError** [comment]
Problem 4.10 is raised when the count of each collected unicode differs from the number of masters for that glyph. This allows multiple unicodes per master, as long as every master has them.

**Comment by LettError** [comment]
![image](https://user-images.githubusercontent.com/1243961/70796496-b661ed80-1da2-11ea-9328-30eedda757c9.png)

**Comment by arrowtype** [comment]
Thanks, Erik!

Is this a new feature? If it's not, do you know offhand if it also works if some masters are missing a unicode value for a glyph, while others have one? Back on Nov 11, it missed this scenario in my case.

**Comment by LettError** [comment]
I think it does, but it is new code. https://github.com/LettError/DesignspaceProblems/blob/c0dc16aa4ca85290910ea3c75dee789362923b16/Lib/designspaceProblems/__init__.py#L39

For each glyph, get the unicodes and count them. Add `None` if it hasn’t one. Then after doing all the masters, the count for each Unicode should be the same as the number of masters. Whenever a Unicode has too few counts, report it. I think that covers it.

**Comment by arrowtype** [comment]
So, I've tried to make a smaller test case, to check on this. I've found that especially if multiple people are working on a larger character set and building new glyphs with something like Glyph Construction, this kind of problem is quite easy to run into. 

I thought that it might miss a couple of different scenarios, but I've done a test, and it seems to be working in each way I can think of.

https://github.com/arrowtype/designspace_problems-unicode-test

```
▶ python designspace_problems-unicode-test.py

[[glyphs: different unicodes in glyph, glyphName: C unicodes: [73] (4, 10)],
[glyphs: different unicodes in glyph, glyphName: B unicodes: [None, 66] (4, 10)],
[glyphs: different unicodes in glyph, glyphName: A unicodes: [65, 128] (4, 10)]]
```

![image](https://user-images.githubusercontent.com/45946693/70831237-04d1b500-1dc0-11ea-96d5-b7069f15138d.png)

Before this, I tried the simpler test of this designspace in the DesignspaceEditor, but it didn't report these problems. I guess maybe that extension just hasn't quite been updated yet?

Cheers for adding/improving these tests! As far as I know, this issue is fine to close.

**Comment by LettError** [comment]
Thanks for this test, @arrowtype! I posted [an update for DesignspaceEdit](https://github.com/LettError/designSpaceRoboFontExtension/commit/d48e7b8f0ae98d46f12785e155628c941b20972d). Aside, I need to review whether it is still necessary to embed designspaceProblems in designspaceEdit. <img width="1003" alt="image" src="https://user-images.githubusercontent.com/1243961/70846032-92131900-1e55-11ea-8111-dd0be9cde1d9.png">

**Comment by LettError** [comment]
Ok, Fixed.
